title: Buddha-Dharma
default_lang: en
author:
  name: 'Buddha Dharma Team'
taxonomies:
  - category
  - tag
  - author
metadata:
  description: 'Free and Open Dharma and Sangha'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
chromeless:
  enabled: false
gitrepo:
    edittreeurl: https://github.com/buddha-dharma/micro-site/tree/master/user
    editlinklocation: menu
    editnotetext: 'Have a suggestion?'
    editlinktext: 'Edit this Page'
    editthemelinklocation: none
    editthemelinktext: 'Site Theme Files'
displaymenuentries:
  enabled: true
menu:
  - text: "MEDITATION.TEXT"
    url:  "MEDITATION.URL"
    external: true
hidehomemenulink: true
hidesidebaronblogpages:
  enabled: false
twittertimeline:
  enabled: false
  url: 'https://twitter.com/hibbittsdesign/lists/cpt-363'
  text: 'A Twitter List by @hibbittsdesign'
  height: 700
cc_license:
  enabled: false
  type: ccby
hidesidebaronblog:
  enabled: '0'
chromelesspages:
  enabled: false
icon:
  post: calendar-o
